language: ruby
rvm:
- 2.2.5
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: oe5unGKIMAKApTk+PTHtTHSuzIRBgLPqkZXEJ8h5oU9XsJv9sCHukqj9FTGFalEIbnzlORhhzygME4ixTDTu+OQiJW/zG5tQX/NeCk0ahgTC+7JhaMuIHoQNehzi6tueYIhsZK1Mk1u7lFjg8TIQiLvw8af8R5Rjh0ZiUCY/fm5BKOT/bS0VxogWWXn7FLVekXhQ4qOAL+U18BX1Nf/gOuQfUIVfuqZJRpU9fFKOH3RZL7m6eBk3DhA4pvZIcth7quG65oCaTsctBBIFjVrYuU6JpeaRAXCO1V8JtNxUboHsIpd7QDzle/ffi3SMe9qcrMdrd+gzhmnB5SLtqW1Ki49k4zgBUyqXa7YQvWBEFP4YDYUmosQ6CmwKT6/I4u5qCV6QuzRdi7ka0hmlPAdOtnSXy8Izkr9oOwAaBEtc5sdXH5kgEDioC4n9bjODFbjPpWNWJqZoeYVGQo8wDlu9FHy9ux2y9WFvGWBi87ygk8jBE9boFW327IkikVlnlKKFQgBkfxEOanXQB5dRWF764jkl9v1M8d1ViOnGv9kcWPzlkIcVUb3Kg7risMlYh3A8jedjNQcftRK7ppunPeJql+IHVFRvfwde94tOi0vN4Xx9B8wL/Sl1UX/j6iyvj831ZFdS+oitlwOQM5/KwabBd0J0ApwRLvlwndMaNe8Iz1o=
